version: "3.9"

services:
  backend_users: 
    build: ./backend/UsersService
    ports: 
      - 3001:3001
    environment:
      DB_URL: mongodb://database/BANKINGAPP
  frontend:
    build: ./frontend
    ports:
      - 3003:3003
  database:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes: 
      - BANKINGAPP:/data/db
volumes:
  BANKINGAPP:

