version: "3.9"

services:
  users: 
    build: ./backend/UsersService
    ports: 
      - 3001:3000
    volumes:
      - ./backend/UsersService:/src
    depends_on:
      - database
    environment:
      DB_URL: mongodb://database:27017
  transaction: 
    build: ./backend/TransactionService
    ports: 
      - 3002:3000
    volumes:
      - ./backend/TransactionService:/src
    depends_on:
      - database
    environment:
      DB_URL: mongodb://database:27017
  frontend:
    build: ./app_frontend
    ports:
      - 3003:3000
    volumes:
      - ./app_frontend/frontend:/src
  database:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes: 
      - mongo_db:/data/db
  nginx:
    image: nginx:latest
    ports:
      - 4000:4000
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - users
      - frontend
      - database
      - transaction
volumes:
  mongo_db:

