version: "3.9"

services:
  database:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes: 
      - mongo_db:/data/db
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    volumes:
      - ./data/kafka:/var/run/docker.sock
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on: 
      - zookeeper
  users: 
    build: ./backend/UsersService
    ports: 
      - 3001:3000
    volumes:
      - ./backend/UsersService:/src
    depends_on:
      - database
      - kafka
    environment:
      - DB_URL: mongodb://database:27017
      - KAFKA_SERVER: kafka:9092
  transaction: 
    build: ./backend/TransactionService
    ports: 
      - 3002:3000
    volumes:
      - ./backend/TransactionService:/src
    depends_on:
      - database
      - kafka
    environment:
      - DB_URL: mongodb://database:27017
      - KAFKA_SERVER: kafka:9092
  frontend:
    build: ./app_frontend
    ports:
      - 3003:3000
    volumes:
      - ./app_frontend/frontend:/app
  nginx:
    image: nginx:latest
    ports:
      - 4000:4000
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - users
      - frontend
      - database
      - transaction
volumes:
  mongo_db:

