apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-deployment
  labels:
    app: transaction-pod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transaction-pod
  template:
    metadata:
      labels:
        app: transaction-pod
    spec:
      containers:
      - name: TransactionsService
        image: codeluminary/bankingapp_transaction
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: transaction
spec:
  selector:
    app: transaction-pod
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

