apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
  labels:
    app: users-pod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users-pod
  template:
    metadata:
      labels:
        app: users-pod
    spec:
      containers:
      - name: UsersService
        image: codeluminary/bankingapp_users
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: users
spec:
  selector:
    app: users-pod
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

